chore: 🤖 Increment spec version to 3002
PolymathNetwork/polymesh-subquery pull request #42
Opened 2022-01-04 18:14 UTC by prashantasdeveloper

2022-01-04 18:23 UTC, polymath-eric approved these changes
LGTM

2022-01-05 10:54 UTC, raycar5 requested changes

2022-01-05 10:54 UTC, raycar5 commented on project.template.yaml
> +              minmax: [3001, 3002],
```suggestion
              minmax: [3002, 3002],
```
Then there should be `[3000,3001] ` below

2022-01-05 12:21 UTC, raycar5 approved these changes

2022-01-05 13:44 UTC, merged